### ISSUE TITLE
MPPT values not present after upgrade to 0.12

### ISSUE THREAD

**Issue by bilbolodz** [volkszaehler/mbmd#146]
After upgrade to version 0.12 MPPT values on my Fronius are no longer supported. Devices "renamed" from Frounis1.1 to SUNSPEC1-1

**Comment by bilbolodz** [comment]
User fault

**Comment by andig** [comment]
0.12 introduced a breaking change in naming that was necessary to fix #135. You should still receive all values under the new name?

**Comment by bilbolodz** [comment]
Delete it please

**Comment by andig** [comment]
Nevermind, thanks for letting me know.
