### ISSUE TITLE
REST API broken in 0.12?

### ISSUE THREAD

**Issue by bilbolodz** [volkszaehler/mbmd#147]
In version 0.10 I was using api call like these:
http://X.X.X.X:8081/api/last/SDM1.2

Now my device became: SDM2-2 but call: http:///X.X.X.X:8081/api/last/SDM2-2 gives: "404 page not found". Call http:///X.X.X.X:8081/api/last/ shows data about all devices.

**Comment by andig** [comment]
Should be fixed in fa6b574a16c002b9d3ec6133c4b32efdd7aaac0c
