### ISSUE TITLE
iem3000 wrong values

### ISSUE THREAD

**Issue by wing84** [volkszaehler/mbmd#154]
after solving #152 i can start, but i get very strange values
https://forum.geizhals.at/files/57237/Image%201.jpg
https://forum.geizhals.at/files/57237/Image%202.jpg

**Comment by wing84** [comment]
I think the problem is that Register+1 is needed.

**Comment by andig** [comment]
Could you email me at cpuidle@gmx.de? It would help if I could access an actual device instead of trial and error.

**Comment by andig** [comment]
ping @wing84

**Comment by andig** [comment]
Closed in #158
