### ISSUE TITLE
Data readings on Kostal Inverter incorrect

### ISSUE THREAD

**Issue by zulautholger** [volkszaehler/mbmd#168]
I'm trying to read Data from my Kostal Plenticore Plus 10.

When I use inspect I get different models with different results. 
Model 103 reads the right values e.g. 2780553.00 for WH.
Model 113 results in values e.g. -2.4630083e-06 for WH.

When I open the API in a browser, it unfortunatly reads the values for Model 113.

How can i change the model or how can i get mbmd to deliver the correct values?

**Comment by andig** [comment]
Could you share the inspect output?

**Comment by zulautholger** [comment]
[kostal_inspect.txt](https://github.com/volkszaehler/mbmd/files/5149155/kostal_inspect.txt)

**Comment by andig** [comment]
@zulautholger could you email me at cpuidle@gmx.de for remote access to the inverter? It would be great if I could fix the broken float readings. I assume this is more an encoding issue.
