### ISSUE TITLE
Documentation/template for configuration YAML

### ISSUE THREAD

**Issue by just-grizzle** [volkszaehler/mbmd#173]
Hi,

I fetched the precompiled binary for ARM and managed to set it up on a RPi as daemon successfully. 
For the sake of beauty, I'd prefer configuration in a YAML file over the command line parameters. E.g. the command gets quite messy, if you have to handle MQTT configuration.

Is there some documentation or template file one could use?

Regards

**Comment by andig** [comment]
How about https://github.com/volkszaehler/mbmd/blob/master/mbmd.dist.yaml ;)

**Comment by just-grizzle** [comment]
Oh yeah, stupid me. Works like a charme. Only command line parameter I still have to add is `-r`. Thank you!
