### ISSUE TITLE
Support for influxdb v1

### ISSUE THREAD

**Issue by fasmide** [volkszaehler/mbmd#181]
I've seen the nice addition of https://github.com/volkszaehler/mbmd/commit/0931fd4f5ab1797353984e75c64e5a64ba20ca72 ... but did this completely remove support for the older influxdb server?

I just tried setting up a new mbmd daemon, and it seems it's unable to communicate with my influxdb database:

```
Nov 24 17:56:41 energy mbmd[1111]: 2020/11/24 17:56:41 [E]! Write error: 404 Not Found: 404 page not found
Nov 24 17:56:41 energy mbmd[1111]: 2020/11/24 17:56:41 influxdb error: 404 Not Found: 404 page not found
```

Taking a look at the traffic on the influxdb machine, it seems it tries to POST to `POST /api/v2/write?bucket=mbmd&org=&precision=ns HTTP/1.1` which is not available on the old influxdb servers...

Does the new influxdb library maybe have a sort of flag that can be set to make it support older influxdb's ?

**Comment by andig** [comment]
You will need to upgrade influx1 to 1.8.3 afaik
