### ISSUE TITLE
Adding ORNO WE-504

### ISSUE THREAD

**Issue by bbiegun** [volkszaehler/mbmd#182]
Hallo zusammen!

I'd like to add a support for ORNO OR-WE-504 one-phase meter.

I'm in the process of building the module up. Based on the previous ORNO meters' names I'm proposing an ORNO1P504 module name. Unfortunately registers are different in number and type from the ORNO1P.

After testing I'll a pull request.

**Comment by bbiegun** [comment]
PR is ready for your review.

**Comment by andig** [comment]
Closed by https://github.com/volkszaehler/mbmd/pull/183
