### ISSUE TITLE
Web server issue on build

### ISSUE THREAD

**Issue by hacor** [volkszaehler/mbmd#214]
Hello 

I made a fork of mbmd to add several extra addresses to the [SDM220 meter](https://github.com/hacor/mbmd/blob/master/meters/rs485/sdm220.go#L25)
The build seems to work fine, but in the newly generated `mbmd` binary the web server seems to fail. I get a 404 error on all css and javascript files.
The `api` part of the web server seems te work perfectly, when I access `http://*.*.*.*:8080/api/status` it gives me the following result:

```json
{"StartTime":"2021-06-30T08:16:33.580522341Z","UpTime":633.844725084,"Goroutines":74,"Memory":{"Alloc":2747736,"HeapAlloc":2747736},"Meters":[{"Device":"SDM2201.1","Type":"SDM220","Online":true,"Requests":490,"RequestsPerMinute":786.3062634664598,"Errors":0,"ErrorsPerMinute":0},{"Device":"SDM2201.2","Type":"SDM220","Online":true,"Requests":490,"RequestsPerMinute":786.3062634664598,"Errors":0,"ErrorsPerMinute":0},{"Device":"SDM2201.3","Type":"SDM220","Online":true,"Requests":490,"RequestsPerMinute":786.3062634664598,"Errors":0,"ErrorsPerMinute":0}]}
```

Only the static files (js, css,...) seem to fail loading.
The build is a cross platform build for raspberry pi 4 .

Maybe I did something wrong.
I hope someone out here can help.
If this works I create a PR.

All the best!

Hacor

**Comment by andig** [comment]
Did you `make` the assets?

**Comment by hacor** [comment]
The build is realised by running the following docker command:

```bash
docker run --rm -e GOOS=linux -e GOARCH=arm -e GOARM=7 -v ${PWD}:/app --workdir=/app golang:1.16 /bin/bash -c "make install && make build"
```
I'm not really sure if this covers your question? I just followed the `README.md` build info

Regards!

H

**Comment by andig** [comment]
Do you have the same problem building without docker?

**Comment by hacor** [comment]
I never used go before, so I didn't really install it on my local machine.
I will give it a try!

**Comment by hacor** [comment]
Also with the local installed Go 1.16 the https assets return a 404. See screenshot...

<img width="955" alt="Schermafbeelding 2021-06-30 om 11 56 47" src="https://user-images.githubusercontent.com/7940367/123941312-53db3d00-d99a-11eb-8ae0-2f7cc45c9050.png">

**Comment by hacor** [comment]
When reading more and more it indeed seems the assets are not `build` into the release.
Do you have any instructions on this?

Thanks

**Comment by hacor** [comment]
@andig By investigating the problem I found out that the master branch Makefile doesn't contain an `assets` option.
A `make assets` command doesn't work, but I see this changed in a [commit](https://github.com/volkszaehler/mbmd/commit/aa0e98212cfb2ba9bc1327ad7526a2ff35faeaa0#diff-76ed074a9305c04054cdebb9e9aad2d818052b07091de1f20cad0bbac34ffb52L25) from may 25.
Can you please suggest how to build the assets now with Go 1.16, or which branch/tag to use for local development? 
I know this is a complete noob question, but after successfully building my adaptations I can create the PR

Thanks!

**Comment by andig** [comment]
Sorry for the confusion, some leftovers in the code, fixed with https://github.com/volkszaehler/mbmd/pull/215
