### ISSUE TITLE
Change default port to something else than 8080?

### ISSUE THREAD

**Issue by sirtet** [volkszaehler/mbmd#228]
As this is part of volkszähler, i think it will often be used in conjunction and on the same machine.
But in such a case, 8080 is already occupied by the default VZ frontend.
So would it not make sense to use a different port by default?

**Comment by andig** [comment]
I wouldn't want to change it at this time to not break people's installations. To my knowledge there is also little overlap in the user groups, although both should work together with some plumbing (i.e. vzlogger).
