### ISSUE TITLE
Add documentation "how to use with volkszähler"?

### ISSUE THREAD

**Issue by sirtet** [volkszaehler/mbmd#229]
I am currently trying to figure out how to use mbmd with VZ.
But he docs here seem not to mention VZ at all...
Would it make sense to add documentation about that to this repo?
I could do a PR once i know how to do it, if that's welcome.
Until then, i am happy about any input, either here or on the [thread](https://www.photovoltaikforum.com/) i opened in the photovoltaikforum, where i detailed what i already got working and where exactly i struggle.

**Comment by andig** [comment]
MBMD works fine without VZ. If you want to document integration, the VZ wiki would be the most appropriate place.
