### ISSUE TITLE
do i need added systemd settings in case of TCP meters?

### ISSUE THREAD

**Issue by sirtet** [volkszaehler/mbmd#231]
I don't know much about systemd, but from comparing with vzlogger.service, i wonder if the service
```
[Unit]
Description=mbmd
After=syslog.target
```

should also wait for network? Probably only in case a network meter is used? Or will it also work if the network comes up later?

**Comment by andig** [comment]
Feel free to send a PR

**Comment by sirtet** [comment]
Sure, i would. 
That's why i ask if it is needed at all or if it even would be harmful in some cases...
Or, should i read your comment as "yes, it would be a good idea" ?
