### ISSUE TITLE
Changle comset

### ISSUE THREAD

**Issue by gigipawel** [volkszaehler/mbmd#241]
I need Changle comset: 8N1  to "8E1"
and I don't know what command to give

" **./mbmd run -a /ttyUSB0 -b 9600 8E1** " did not work :( 

:~$ ./mbmd run -a /dev/ttyUSB0 -b 9600   8E1
2022/01/01 21:53:41 mbmd 0.13 (fa6b574)
2022/01/01 21:53:41 excess arguments, aborting: [8E1]

**Comment by andig** [comment]
See https://github.com/volkszaehler/mbmd/blob/master/docs/mbmd_run.md
