### ISSUE TITLE
New meter supported! ET340

### ISSUE THREAD

**Issue by crazycusti** [volkszaehler/mbmd#261]
Hey!

i have a et340 energy meter with modbus rtu support from carlo gavazzi

the newest em24 support was very helpful last days ago! the et340 had the same registers. all working fine :)!

thank you for the support!

**Comment by andig** [comment]
Thanks for letting me know! Will update the docs to include et340.

**Comment by andig** [comment]
Closed via https://github.com/volkszaehler/mbmd/commit/a8df462944078242755ce2187d4e0b41fda3a3d5
