### ISSUE TITLE
ORNO WE 516 wrong data to mqtt

### ISSUE THREAD

**Issue by mkmt** [volkszaehler/mbmd#274]
Running command:

mbmd run -a /dev/tty.usb-1.1.4 -d ORNO3P:1 --raw --comset 8E1 -r 60s -m tcp://127.0.0.1:1883

gives me right values in web interface but completely wrong in mqtt, like:

...
homie/orno3p1-1/meter/voltagel1/$name L1 Voltage
homie/orno3p1-1/meter/voltagel1/$unit V
homie/orno3p1-1/meter/voltagel1/$datatype float
homie/orno3p1-1/meter/currentl1/$name L1 Current
homie/orno3p1-1/meter/currentl1/$unit A
...

Seems to be an error in mbmd code.

**Comment by andig** [comment]
What is wrong? Observed value vs actual value?

**Comment by mkmt** [comment]
@andig there is no value, instead of value I get what I think is name of variable, like in:

homie/orno3p1-1/meter/voltagel1/$name L1 Voltage

**Comment by andig** [comment]
Value should be in 

    homie/orno3p1-1/meter/voltagel1

**Comment by mkmt** [comment]
@andig yes it should but instead of valu in mqtt I get this:

...

**Comment by mkmt** [comment]
Solved, just few first mqtt messages are like that, rest are normal.

By the way it is still a bug worth notiecing.

**Comment by andig** [comment]
Closing as its not clear if that's an issue on mbmd side or related to the meter.
