### ISSUE TITLE
Latest nightly - Modbus TCP - Gaps in Reading

### ISSUE THREAD

**Issue by isarrider** [volkszaehler/mbmd#277]
Hi,

compared to the build I made on June 11 (with the current master branch then),
the latest nightly has gaps (like every 7s one reading) in reading for me...
See picture attached - revert to the nightly before the commit in the ~last 20%...
![Clipboard01](https://user-images.githubusercontent.com/6953309/188273162-f2157244-c8e2-4dea-8f2c-fa26a3ba62d5.png)

The commit afterwards - thought it is only related to Modbus RTU?

BR,
Alex

**Comment by andig** [comment]
Can you bisect to the breaking commit?

**Comment by isarrider** [comment]
basically already did, as only one commit is after
(the other only changes the systemd requirements for startup)

**Comment by andig** [comment]
Which commit?

**Comment by isarrider** [comment]
if its no other tings, must be #265

**Comment by andig** [comment]
That will add timeout for TCP, too: https://github.com/volkszaehler/mbmd/pull/265/files#diff-30e0f5e75378b29cffb17ecc20d5fe46e5fbf95b4952a60cb55cba0ade588e37R92. Can you try if increasing the timeout fixes your problem?

**Comment by isarrider** [comment]
was afraid of that
(whats the default timeout in contrast to before the commit?)
Ill figure out how to add this in the config file and post the result here...

**Comment by isarrider** [comment]
couldnt figure out until now where the timeout can be specified in the config.yaml
(https://github.com/volkszaehler/mbmd/blob/master/mbmd.dist.yaml)
Ill try to use an edited source file with:

const DefaultTimeout = 900 * time.Millisecond

in commons.go

**Comment by tobima** [comment]
The default should be unchanged and still be 300ms.

You could use the cmdline parameter `--timeout` to change the timeout. E,g. '--timeout 600ms' to change the timeout to 600ms.
The format for the duration is documented here:  https://pkg.go.dev/time#ParseDuration

I haven't invest any time so far to understand how the config file.

**Comment by isarrider** [comment]
ok, it seems with the 900ms, the timeout doenst occur for me anymore,
I get measurements now every second... (latest nightly b2590ae (compiled with go1.19))
Maybe the timeout should be by default higher than 300ms?

**Comment by isarrider** [comment]
closing it here...
