### ISSUE TITLE
Parity per device

### ISSUE THREAD

**Issue by mkmt** [volkszaehler/mbmd#280]
Is it possible to add new future to set parity per device not per instance. So it is possible to pull data from few meters with different parity? Like for example Orno WE 516 and Orno WE 504 connected to same rs485?

Right now I had to write own scripts to pull data from meters, can't use MBMD to do the job.

I imagine it should be possible since I was able to do that in python script.

**Comment by premultiply** [comment]
No, all devices on same rs485 serial line have to use exactly the same basic communication parameters and also should use the same protocol (Modbus RTU).

You may have luck under special condition to switch parameters by opening and closing the serial port as master on a single master system but there is no gurantee that all devices remain in a clear state or that they even do not talk to the shared line in between as they do not really understand what is going on.
So most of the time this will end up in garbage. Do not do it this way. It is just not designed to support such scenarios.
