### ISSUE TITLE
Carlo Gavazzi Implementation

### ISSUE THREAD

**Issue by Dennis572687** [volkszaehler/mbmd#301]
Hi,
today i installed the Volkszaehler on a raspi and i'm using mbmd to pull data from my Carlo Gavazzi ET340 meter.
I noticed that some of the readings are wrong and i looked into your code.
I also noticed that you changed something because there was an issue with the modbus registers.

But the real problem seems to be the following:
Carlo Gavazzi is using two different sets of registers.
One set for the EM24 meter, and another Set for the EM330, EM340, ET330 and ET340 meters.
I added the two different descriptions of the communication protocol:
[em24_is_cp.pdf](https://github.com/volkszaehler/mbmd/files/10538386/em24_is_cp.pdf)
[EM330_EM340_ET330_ET340_CP.pdf](https://github.com/volkszaehler/mbmd/files/10538388/EM330_EM340_ET330_ET340_CP.pdf)
I also made a comparison:
![Unbenannt](https://user-images.githubusercontent.com/123981152/215561288-fd7f97ff-efaa-4f86-b806-4ca4cbf8f571.PNG)

So i guess two different "Device-Codes" are needed to handle this properly.
The CGEM24 and a new CGEx3x0 or whatever you want to call it ;)

**Comment by andig** [comment]
Thank you @Dennis572687, that is very good insight and explains the confusion. Very unfortunate. Do you want to provide a PR (or would you be able to test one)?
