### ISSUE TITLE
Panic runtime error after RPi upgrade.

### ISSUE THREAD

**Issue by krawcu183** [volkszaehler/mbmd#314]
After RPi upgrade I have following errors. It was working before that for few years.

/usr/local/bin/mbmd scan -a /dev/ttyUSB0

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x163128]

goroutine 1 [running]:
regexp/syntax.Parse(0x0, 0xd, 0xd4, 0x76ecb0, 0x1c7ca01, 0x1d723c0)
        /home/travis/.gimme/versions/go1.13.linux.amd64/src/regexp/syntax/parse.go:724 +0xac
regexp.compile(0x0, 0xd, 0x10000d4, 0x1c71980, 0x1c71960, 0x0)
        /home/travis/.gimme/versions/go1.13.linux.amd64/src/regexp/regexp.go:170 +0x2c
regexp.Compile(...)
        /home/travis/.gimme/versions/go1.13.linux.amd64/src/regexp/regexp.go:133
regexp.MustCompile(0x0, 0xd, 0x0)
        /home/travis/.gimme/versions/go1.13.linux.amd64/src/regexp/regexp.go:309 +0x34
gopkg.in/ini%2ev1.init()
        /home/travis/gopath/pkg/mod/gopkg.in/ini.v1@v1.55.0/ini.go:40 +0x24

**Comment by andig** [comment]
You are running amd64 on pi???
