### ISSUE TITLE
Support for Kostal Plenticore G2

### ISSUE THREAD

**Issue by capu-bia** [volkszaehler/mbmd#315]
The Kostal inverter sends some strange data. Is there a possibility to solve this problem?
Tried it with device type "Kostal" and "Suns".
![mbmd](https://user-images.githubusercontent.com/97593681/234791985-e6695e5c-a4ab-490a-a332-6690e2b28346.JPG)

**Comment by andig** [comment]
Contact Kostal support. Sunspec is standardised- looks like Kostal has Problems with that?

**Comment by andig** [comment]
If you want to speak sunspec you'll have to set it to sunspec I guess. It remains a mystery to my if/why Kostal would change the meaning of the sunspec registers with this settings. Sunspec is standardised...
