### ISSUE TITLE
Web frontend is no longer working on current Chromium based browsers

### ISSUE THREAD

**Issue by sicheste** [volkszaehler/mbmd#345]
Hi,

on Chromium based browsers (e.g MS Edge, Google Chrome, DuckDuckGo app) the web frontend is no longer working. It is only showing "Loading..." for the measurements and that's it.

I cannot tell since when exactly or since which version it is no longer working. I am not using it so often.

**Comment by SchumacherFM** [comment]
Try this branch if you can self compile https://github.com/volkszaehler/mbmd/pull/342
the bug is here fixed https://github.com/volkszaehler/mbmd/pull/341/files

![mbmb](https://github.com/volkszaehler/mbmd/assets/372027/76e9630b-15e8-43c8-8716-a9b788797736)

**Comment by sicheste** [comment]
Yes, #341 is solving the issue. Thanks.
