### ISSUE TITLE
Adding support for meter SDM54

### ISSUE THREAD

**Issue by kiezematze** [volkszaehler/mbmd#351]
I have prepared a pr adding support for the Eastron SDM54 meter. 
As this is my first PR on GitHub I  for this and I want to follow the procedure: create issue -> create branch -> submit PR

**Comment by kiezematze** [comment]
Can anybody out there please help me create a branch for this issue?

**Comment by kiezematze** [comment]
OK, I see, I need write permissions.

**Comment by andig** [comment]
Done
