### ISSUE TITLE
Throttling for Influxdb

### ISSUE THREAD

**Issue by bilbolodz** [volkszaehler/mbmd#66]
There should be a possibility to throttle data sent do Influxdb. Ideal solution (for me of course) is to set separate frequency of pooling device BUT throttle frequency of Influxdb updates. Maybe it also could be good idea (for some parameters) send data to Influxdb ONLY on value change.

**Comment by andig** [comment]
Not a short term priority.

**Comment by andig** [comment]
Closing as wontfix
