### ISSUE TITLE
Add support for MPPT values from Sunspec compatible inverters

### ISSUE THREAD

**Issue by bilbolodz** [volkszaehler/mbmd#70]
Add support for MPPT values from Sunspe compatible inverters: "model160" contain that values, but number of blocks (each string in separate block) depends on inverter model.

**Comment by andig** [comment]
Would like to add that but need an inverter for testing. Mine don‘t speak modbus. Would you potentially grant remote access per ssh? Please pm me at cpuidle@gmx.de.

**Comment by bilbolodz** [comment]
I've sent your an email about details.

**Comment by bilbolodz** [comment]
Next email sent ;-)

**Comment by bilbolodz** [comment]
Another email sent.

**Comment by andig** [comment]
Fixed via #73
