### ISSUE TITLE
add option to chose port of web interface

### ISSUE THREAD

**Issue by kartenkarsten** [volkszaehler/mbmd#78]
I have to query two different modbus tcp devices. Therefore I need to start two instances of mbmd. Unluckly it is not possible on the same machine because the port of web interface is hard coded to 8080.

please add an option to change this.

**Comment by andig** [comment]
> please add an option to change this.

Did you try:

	mbmd run --help

The switch is `--api`:

	Read and publish measurements from all configured devices

	Usage:
	  mbmd run [flags]

	Flags:
	      --api string                  REST API url. Use 127.0.0.1:8080 to limit to localhost. (default "0.0.0.0:8080")
	  -d, --devices strings             MODBUS device type and ID to query, multiple devices separated by comma or by repeating the flag.

> Therefore I need to start two instances of mbmd. 

No need to do that! We have a verbose config file that allows specifying multiple devices: https://github.com/volkszaehler/mbmd/blob/master/mbmd.dist.yaml. Rename to `mbmd.yaml` and you're ready to go.
