### ISSUE TITLE
After building unfortunately no data

### ISSUE THREAD

**Issue by klauskn** [volkszaehler/mbmd#87]
When I try to build on my Raspberry 4, I get no error message but unfortunately no data in the web interface. 
On the console they are printed with -v.  
Anyone have an idea?

![grafik](https://user-images.githubusercontent.com/20045785/73875422-948e5f80-4855-11ea-9511-37d950beae64.png)

**Comment by andig** [comment]
Whats in the browser console?

**Comment by klauskn** [comment]
Source-Map-Fehler: Error: request failed with status 404
Ressourcen-Adresse: http://volkszaehler:8088/css/bootstrap.min.css
Source-Map-Adresse: bootstrap.min.css.map

Die Verbindung zu ws://volkszaehler:8088/ws wurde unterbrochen, während die Seite geladen wurde.

**Comment by klauskn** [comment]
Excuse me, I just realized that 
data are displayed correctly on another PC.
After I have deleted the cache on the 1st PC, I see data there as well. So everything works as expected.
