### ISSUE TITLE
Errors and errors per minute SDM630

### ISSUE THREAD

**Issue by wisekki** [volkszaehler/mbmd#89]
Hi, I was looking at the json result that the mbmd sends and I noticed that there are "Errors" and "ErrorsPerMinute" which increase steadily after a few hours of running the mbmd. What are these? Are they related to: 
>2020/02/12 10:27:03 device SDM1.1 did not respond (1/3)

After restarting the software it takes a few minutes and then they start:

> 0: {Device: "SDM1.1", Type: "SDM", Online: true, Requests: 252, RequestsPerMinute: 19.379029257344072,…}
Device: "SDM1.1"
Type: "SDM"
Online: true
Requests: 252
RequestsPerMinute: 19.379029257344072
Errors: 3
ErrorsPerMinute: 0.2307027292540961

Below is a short log from raw output. 

> 2020/02/12 10:19:24 modbus: send 01 04 00 0e 00 02 10 08
2020/02/12 10:19:24 modbus: recv 01 04 04 00 00 00 00 fb 84
2020/02/12 10:19:24 modbus: send 01 04 01 6a 00 02 50 2b
2020/02/12 10:19:24 modbus: recv 01 04 04 45 a2 26 c7 14 98
2020/02/12 10:19:24 modbus: send 01 04 00 ea 00 02 50 3f
2020/02/12 10:19:24 modbus: recv 01 04 04 3f e3 c9 61 91 de
2020/02/12 10:19:24 modbus: send 01 04 00 ee 00 02 11 fe
2020/02/12 10:19:24 modbus: recv 01 04 04 40 d5 73 45 1b 7f
2020/02/12 10:19:24 modbus: send 01 04 00 0c 00 02 b1 c8
2020/02/12 10:19:24 modbus: recv 01 04 04 41 fa 17 7c c1 98
2020/02/12 10:19:24 modbus: send 01 04 00 38 00 02 f0 06
2020/02/12 10:19:24 modbus: recv 01 04 04 41 fc 71 09 cb de
2020/02/12 10:19:24 modbus: send 01 04 01 5c 00 02 b0 25
2020/02/12 10:19:24 modbus: recv 01 04 04 45 9d 98 31 d5 72
2020/02/12 10:19:24 modbus: send 01 04 01 60 00 02 70 29
2020/02/12 10:19:24 modbus: recv 01 04 04 00 00 00 00 fb 84
2020/02/12 10:19:24 modbus: send 01 04 01 56 00 02 90 27
2020/02/12 10:19:24 modbus: recv 01 04 04 46 85 73 f0 da 51
2020/02/12 10:19:24 modbus: send 01 04 00 00 00 02 71 cb
2020/02/12 10:19:24 modbus: recv 01 04 04 43 6c 8a 2d 89 60
2020/02/12 10:19:24 modbus: send 01 04 00 02 00 02 d0 0b
2020/02/12 10:19:24 modbus: recv 01 04 04 43 6e 80 4e 6e 29
2020/02/12 10:19:24 modbus: send 01 04 00 0a 00 02 51 c9
2020/02/12 10:19:24 modbus: recv 01 04 04 00 00 00 00 fb 84
2020/02/12 10:19:24 modbus: send 01 04 01 66 00 02 90 28
2020/02/12 10:19:24 modbus: recv 01 04 04 45 d6 10 c9 c2 e6
2020/02/12 10:19:24 modbus: send 01 04 00 22 00 02 d1 c1
2020/02/12 10:19:24 modbus: recv 01 04 04 3f 80 00 00 f6 78
2020/02/12 10:19:24 modbus: send 01 04 00 46 00 02 90 1e
2020/02/12 10:19:24 modbus: recv 01 04 04 42 48 06 48 6c 7c
2020/02/12 10:19:24 modbus: send 01 04 00 04 00 02 30 0a
2020/02/12 10:19:24 modbus: recv 01 04 04 43 6e 28 f1 50 59
2020/02/12 10:19:24 modbus: send 01 04 01 5a 00 02 50 24
2020/02/12 10:19:24 modbus: recv 01 04 04 45 d6 10 c9 c2 e6
2020/02/12 10:19:24 modbus: send 01 04 00 06 00 02 91 ca
2020/02/12 10:19:24 modbus: recv 01 04 04 3e 09 b4 22 d1 77
2020/02/12 10:19:24 modbus: send 01 04 00 34 00 02 30 05
2020/02/12 10:19:24 modbus: recv 01 04 04 41 fc 2e 9a b2 43
2020/02/12 10:19:24 modbus: send 01 04 01 64 00 02 31 e8
2020/02/12 10:19:24 modbus: recv 01 04 04 00 00 00 00 fb 84
2020/02/12 10:19:24 modbus: send 01 04 00 08 00 02 f0 09
2020/02/12 10:19:24 modbus: recv 01 04 04 00 00 00 00 fb 84
2020/02/12 10:19:24 modbus: send 01 04 00 3c 00 02 b1 c7
2020/02/12 10:19:24 modbus: recv 01 04 04 00 00 00 00 fb 84
2020/02/12 10:19:24 modbus: send 01 04 00 54 00 02 30 1b
2020/02/12 10:19:24 modbus: recv 01 04 04 41 fc 2b 66 b1 52
2020/02/12 10:19:24 modbus: send 01 04 00 48 00 02 f1 dd
2020/02/12 10:19:24 modbus: recv 01 04 04 46 85 73 f0 da 51
2020/02/12 10:19:24 modbus: send 01 04 01 68 00 02 f1 eb
2020/02/12 10:19:24 modbus: recv 01 04 04 45 9d 98 31 d5 72
2020/02/12 10:19:24 modbus: send 01 04 00 10 00 02 70 0e
2020/02/12 10:19:24 modbus: recv 01 04 04 00 00 00 00 fb 84
2020/02/12 10:19:24 modbus: send 01 04 01 62 00 02 d1 e9
2020/02/12 10:19:25 modbus: recv 01 04 04 00 00 00 00 fb 84
2020/02/12 10:19:25 modbus: send 01 04 00 4a 00 02 50 1d
2020/02/12 10:19:25 modbus: recv 01 04 04 00 00 00 00 fb 84
2020/02/12 10:19:25 modbus: send 01 04 00 3e 00 02 10 07
2020/02/12 10:19:25 modbus: recv 01 04 04 3f 79 c3 9d b7 10
2020/02/12 10:19:25 modbus: send 01 04 00 ec 00 02 b0 3e
2020/02/12 10:19:25 modbus: recv 01 04 04 40 0c 8b d4 48 e8
2020/02/12 10:19:25 modbus: send 01 04 01 5e 00 02 11 e5
2020/02/12 10:19:25 modbus: recv 01 04 04 45 a2 26 c7 14 98
2020/02/12 10:19:25 modbus: send 01 04 00 1e 00 02 11 cd
2020/02/12 10:19:25 modbus: recv 01 04 04 3f 7d b2 a1 d2 90
2020/02/12 10:19:25 modbus: send 01 04 00 20 00 02 70 01
2020/02/12 10:19:25 modbus: recv 01 04 04 3f 80 00 00 f6 78
2020/02/12 10:19:25 modbus: send 01 04 00 f8 00 02 f0 3a

**Comment by andig** [comment]
Yes, these are related.
