### ISSUE TITLE
Rest API not working with release binary

### ISSUE THREAD

**Issue by mdk2412** [volkszaehler/mbmd#95]
Since updating sdm630 0.6.0 to mbmd release the rest API does not work anymore. Calling http://****:8080/last/ (same with avg, status) gives "404 page not found", ws gives "bad request".

The main page http://****:8080 shows the correct data.

What am I doing wroing?

**Comment by andig** [comment]
Are you tying the api to 0.0.0.0?

**Comment by mdk2412** [comment]
systemd status states "httpd: starting api at 0.0.0.0:8080". Accessing http://****:8080/ in firefox shows normal realtime stats. http://****:8080/last gives "404 page not found". http://****:8080/ws gives "Bad Request". Same with "curl -s".

**Comment by andig** [comment]
Ahh, sorry. I forgot and the docs are not clear enough- all REST endpoints are below `/api` and `/ws` won't work if you try to http-connect to it.
